### PR TITLE
Feature generic classes

### PR DESCRIPTION
**Pull request by nilsauf**
Hi,

this PR enables the generator to generate code for generic classes, fixing #117 in the process. It also handels type constraints. 
I had to change a few things, but the rest should work as expected. Take your time to review it.

Feel free to contact me for any questions.

### CODE REVIEW

**Comment by glennawatson** [comment]
Thanks for the reminder. This one slipped through the cracks. Thanks again

**Comment by nilsauf** [comment]
Is it possible to deploy a release from the main branch?

**Comment by glennawatson** [comment]
See https://github.com/reactivemarbles/ObservableEvents/releases/tag/1.2.3

**Comment by nilsauf** [comment]
Tanks!

**Pull request merged**
